<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-9MEI8NR" failures="1" tests="1" name="tla-tesNG(failed)" time="8.885" errors="0" timestamp="2022-07-16T21:34:06 EDT">
  <testcase classname="tests.HomeTest" name="test04" time="2.301">
    <failure type="java.lang.AssertionError" message="pass expected [The Internetz] but found [The Internet]">
      <![CDATA[java.lang.AssertionError: pass expected [The Internetz] but found [The Internet]
at tests.HomeTest.test04(HomeTest.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test04 -->
  <testcase classname="tests.HomeTest" name="test01" time="0.0">
    <ignored/>
  </testcase> <!-- test01 -->
  <testcase classname="tests.HomeTest" name="test03" time="0.0">
    <ignored/>
  </testcase> <!-- test03 -->
  <testcase classname="tests.HomeTest" name="test02" time="0.0">
    <ignored/>
  </testcase> <!-- test02 -->
</testsuite> <!-- tla-tesNG(failed) -->
